-- Add Smart Auto-Routing fields to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS enableSmartRouting INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS smartRoutingFolder VARCHAR(255),
ADD COLUMN IF NOT EXISTS smartRoutingStartingPoint TEXT,
ADD COLUMN IF NOT EXISTS autoOptimizeRoutes INT NOT NULL DEFAULT 1;

-- Add isAutoGenerated field to routes table
ALTER TABLE routes
ADD COLUMN IF NOT EXISTS isAutoGenerated BOOLEAN NOT NULL DEFAULT FALSE;

-- Show confirmation
SELECT 'Smart Routing columns added successfully!' AS status;
