import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, int, varchar, text, timestamp, mysqlEnum, decimal } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const accountSettings = mysqlTable("account_settings", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	businessName: varchar({ length: 255 }),
	businessAddress: text(),
	businessPhone: varchar({ length: 50 }),
	businessEmail: varchar({ length: 320 }),
	businessLogo: text(),
	taxId: varchar({ length: 50 }),
	invoicePrefix: varchar({ length: 20 }).default('INV'),
	nextInvoiceNumber: int().default(1000).notNull(),
	invoiceFooter: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("userId").on(table.userId),
]);

export const billingRecords = mysqlTable("billing_records", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	routeId: int().notNull(),
	clientId: int().notNull(),
	routeHolderId: int().notNull(),
	routeName: varchar({ length: 255 }).notNull(),
	routeDate: timestamp({ mode: 'string' }).notNull(),
	completedAt: timestamp({ mode: 'string' }).notNull(),
	billingModel: mysqlEnum(['mileage','flat_fee','hourly']).notNull(),
	totalMiles: int(),
	mileageRate: int(),
	totalHours: int(),
	hourlyRate: int(),
	flatFeeAmount: int(),
	calculatedAmount: int().notNull(),
	invoiceNumber: varchar({ length: 50 }),
	invoiceDate: timestamp({ mode: 'string' }),
	paidAt: timestamp({ mode: 'string' }),
	paymentMethod: varchar({ length: 50 }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const cachedContacts = mysqlTable("cached_contacts", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	address: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	googleResourceName: varchar({ length: 255 }),
	phoneNumbers: text(),
	photoUrl: text(),
	labels: text(),
	isActive: int().default(1).notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	importantDates: text(),
	comments: text(),
	originalAddress: text(),
	addressModified: int().default(0),
	addressModifiedAt: timestamp({ mode: 'string' }),
	addresses: text(),
	scheduledDays: text(),
	repeatInterval: int().default(1),
	repeatDays: text(),
	scheduleEndType: mysqlEnum(['never','date','occurrences']).default('never'),
	scheduleEndDate: timestamp({ mode: 'string' }),
	scheduleEndOccurrences: int(),
	currentOccurrenceCount: int().default(0),
	scheduleStartDate: timestamp({ mode: 'string' }),
	routeHolderSchedule: text(),
	isOneTimeVisit: int().default(0),
	oneTimeVisitDate: timestamp({ mode: 'string' }),
	oneTimeRouteHolderId: int(),
	oneTimeStopType: varchar({ length: 100 }),
	oneTimeStopTypeColor: varchar({ length: 7 }),
});

export const calendars = mysqlTable("calendars", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 100 }).notNull(),
	color: varchar({ length: 7 }).default('#3b82f6').notNull(),
	isDefault: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const clients = mysqlTable("clients", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	routeHolderId: int().notNull(),
	clientName: varchar({ length: 255 }).notNull(),
	contactName: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	address: text(),
	billingModel: mysqlEnum(['mileage','flat_fee','hourly']).notNull(),
	mileageRate: int(),
	flatFeeAmount: int(),
	hourlyRate: int(),
	paymentTerms: varchar({ length: 100 }).default('Net 30'),
	notes: text(),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const commentOptions = mysqlTable("comment_options", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	option: varchar({ length: 255 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const contactDocuments = mysqlTable("contact_documents", {
	id: int().autoincrement().notNull(),
	contactId: int().notNull(),
	userId: int().notNull(),
	fileName: varchar({ length: 255 }).notNull(),
	fileKey: text().notNull(),
	fileUrl: text().notNull(),
	fileSize: int().notNull(),
	mimeType: varchar({ length: 100 }).notNull(),
	uploadedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const dashboardPreferences = mysqlTable("dashboard_preferences", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	widgetVisibility: text(),
	widgetOrder: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("userId").on(table.userId),
]);

export const folders = mysqlTable("folders", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	color: varchar({ length: 7 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const importantDateTypes = mysqlTable("important_date_types", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 100 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	showOnWaypoint: int().default(0).notNull(),
});

export const labelColors = mysqlTable("label_colors", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	labelName: varchar({ length: 255 }).notNull(),
	color: varchar({ length: 7 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("unique_user_label").on(table.userId, table.labelName),
]);

export const loginAttempts = mysqlTable("login_attempts", {
	id: int().autoincrement().notNull(),
	userId: int(),
	email: varchar({ length: 320 }),
	success: int().notNull(),
	failureReason: varchar({ length: 255 }),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	loginMethod: varchar({ length: 64 }),
	attemptedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const reminderHistory = mysqlTable("reminder_history", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	contactId: int().notNull(),
	contactName: varchar({ length: 255 }).notNull(),
	dateType: varchar({ length: 100 }).notNull(),
	importantDate: varchar({ length: 50 }).notNull(),
	reminderType: varchar({ length: 50 }).notNull(),
	sentTo: text().notNull(),
	sentAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	status: mysqlEnum(['success','failed']).notNull(),
	errorMessage: text(),
});

export const rescheduleHistory = mysqlTable("reschedule_history", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	waypointId: int().notNull(),
	routeId: int().notNull(),
	routeName: varchar({ length: 255 }).notNull(),
	contactName: varchar({ length: 255 }).notNull(),
	address: text().notNull(),
	originalDate: timestamp({ mode: 'string' }),
	rescheduledDate: timestamp({ mode: 'string' }).notNull(),
	missedReason: text(),
	status: mysqlEnum(['pending','completed','re_missed','cancelled']).default('pending').notNull(),
	completedAt: timestamp({ mode: 'string' }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const routeHolders = mysqlTable("route_holders", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	googleCalendarId: varchar({ length: 255 }),
	defaultStopType: varchar({ length: 100 }),
	defaultStopTypeColor: varchar({ length: 7 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	defaultStartingAddress: text(),
});

export const routeNotes = mysqlTable("route_notes", {
	id: int().autoincrement().notNull(),
	routeId: int().notNull(),
	userId: int().notNull(),
	note: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("routeId_idx").on(table.routeId),
	index("userId_idx").on(table.userId),
]);

export const routeWaypoints = mysqlTable("route_waypoints", {
	id: int().autoincrement().notNull(),
	routeId: int().notNull(),
	contactId: int(),
	position: int().notNull(),
	contactName: varchar({ length: 255 }),
	address: text().notNull(),
	latitude: varchar({ length: 32 }),
	longitude: varchar({ length: 32 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	phoneNumbers: text(),
	photoUrl: text(),
	stopType: varchar({ length: 100 }).default('other'),
	stopColor: varchar({ length: 7 }).default('#3b82f6'),
	isGapStop: int().default(0).notNull(),
	gapDuration: int(),
	gapDescription: text(),
	status: mysqlEnum(['pending','in_progress','complete','missed']).default('pending'),
	executionOrder: int(),
	completedAt: timestamp({ mode: 'string' }),
	missedReason: text(),
	executionNotes: text(),
	rescheduledDate: timestamp({ mode: 'string' }),
	needsReschedule: int().default(0),
	contactLabels: text(),
	importantDates: text(),
	comments: text(),
	calendarEventId: varchar({ length: 255 }),
	addressType: varchar({ length: 50 }),
	gapStopAddress: text(),
	gapStopMiles: decimal({ precision: 10, scale: 2 }),
	gapStopTripType: mysqlEnum(['round_trip','one_way']),
});

export const routes = mysqlTable("routes", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 255 }).notNull(),
	shareId: varchar({ length: 32 }).notNull(),
	isPublic: int().default(0).notNull(),
	totalDistance: int(),
	totalDuration: int(),
	optimized: int().default(1).notNull(),
	hasManualOrder: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	folderId: int(),
	notes: text(),
	shareToken: varchar({ length: 36 }),
	isPubliclyAccessible: int().default(0).notNull(),
	sharedAt: timestamp({ mode: 'string' }),
	completedAt: timestamp({ mode: 'string' }),
	startingPointAddress: text(),
	distanceUnit: mysqlEnum(['km','miles']).default('km'),
	scheduledDate: timestamp({ mode: 'string' }),
	calendarId: int(),
	isArchived: int().default(0).notNull(),
	archivedAt: timestamp({ mode: 'string' }),
	googleCalendarId: varchar({ length: 255 }),
	isAutoGenerated: int().default(0).notNull(),
	routeHolderId: int(),
},
(table) => [
	index("routes_shareId_unique").on(table.shareId),
	index("routes_shareToken_unique").on(table.shareToken),
]);

export const savedStartingPoints = mysqlTable("saved_starting_points", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 100 }).notNull(),
	address: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const schedulerNotes = mysqlTable("scheduler_notes", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	noteText: text().notNull(),
	isCompleted: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	completedAt: timestamp({ mode: 'string' }),
});

export const stopTypes = mysqlTable("stop_types", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	name: varchar({ length: 100 }).notNull(),
	color: varchar({ length: 7 }).default('#3b82f6').notNull(),
	isDefault: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	openId: varchar({ length: 64 }).notNull(),
	name: text(),
	email: varchar({ length: 320 }),
	loginMethod: varchar({ length: 64 }),
	role: mysqlEnum(['user','admin']).default('user').notNull(),
	subscriptionTier: mysqlEnum(['free','premium','enterprise']).default('free').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	preferredCallingService: mysqlEnum(['phone','google-voice','whatsapp','skype','facetime']).default('phone'),
	distanceUnit: mysqlEnum(['km','miles']).default('km'),
	defaultStartingPoint: text(),
	reminderEmail30DaysSubject: text(),
	reminderEmail30DaysBodyContact: text(),
	reminderEmail30DaysBodyTeam: text(),
	reminderEmail10DaysSubject: text(),
	reminderEmail10DaysBodyContact: text(),
	reminderEmail10DaysBodyTeam: text(),
	reminderEmail5DaysSubject: text(),
	reminderEmail5DaysBodyContact: text(),
	reminderEmail5DaysBodyTeam: text(),
	reminderEmailPastDueSubject: text(),
	reminderEmailPastDueBodyContact: text(),
	reminderEmailPastDueBodyTeam: text(),
	defaultStopDuration: int().default(30),
	eventDurationMode: mysqlEnum(['stop_only','include_drive']).default('stop_only'),
	googleCalendarAccessToken: text(),
	googleCalendarRefreshToken: text(),
	googleCalendarTokenExpiry: timestamp({ mode: 'string' }),
	googleCalendarList: text(),
	calendarPreferences: text(),
	autoArchiveDays: int(),
	schedulingEmail: varchar({ length: 320 }),
	enableDateReminders: int().default(0).notNull(),
	reminderIntervals: text(),
	enabledReminderDateTypes: text(),
	defaultStopType: varchar({ length: 100 }),
	defaultStopTypeColor: varchar({ length: 7 }),
	googleContactsAccessToken: text(),
	googleContactsRefreshToken: text(),
	googleContactsTokenExpiry: timestamp({ mode: 'string' }),
	allowMultipleVisits: int().default(0).notNull(),
	enableSmartRouting: int().default(0).notNull(),
	smartRoutingFolder: varchar({ length: 255 }),
	smartRoutingStartingPoint: text(),
	autoOptimizeRoutes: int().default(1).notNull(),
},
(table) => [
	index("users_openId_unique").on(table.openId),
]);
