-- Add Smart Auto-Routing columns to users table
ALTER TABLE `users` 
ADD COLUMN IF NOT EXISTS `enableSmartRouting` INT DEFAULT 0 COMMENT 'Enable/disable Smart Auto-Routing feature',
ADD COLUMN IF NOT EXISTS `smartRoutingFolder` VARCHAR(255) DEFAULT NULL COMMENT 'Default folder for auto-generated routes',
ADD COLUMN IF NOT EXISTS `smartRoutingStartingPoint` TEXT DEFAULT NULL COMMENT 'Default starting point for auto-generated routes',
ADD COLUMN IF NOT EXISTS `autoOptimizeRoutes` INT DEFAULT 1 COMMENT 'Auto-optimize route waypoint order';

-- Add scheduledDays column to cached_contacts table
ALTER TABLE `cached_contacts`
ADD COLUMN IF NOT EXISTS `scheduledDays` TEXT DEFAULT NULL COMMENT 'Comma-separated list of days (e.g., Monday, Wednesday, Friday)';

-- Add isAutoGenerated column to routes table
ALTER TABLE `routes`
ADD COLUMN IF NOT EXISTS `isAutoGenerated` INT DEFAULT 0 COMMENT 'Flag to indicate if route was auto-generated by Smart Routing';
