import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Calendar, MapPin, Users, ChevronRight } from "lucide-react";
import { useLocation } from "wouter";

export default function SmartRoutingDashboard() {
  const { user, loading: authLoading } = useAuth();
  const [, setLocation] = useLocation();

  // Fetch all contacts with scheduled days
  const { data: contacts, isLoading: contactsLoading } = trpc.contacts.list.useQuery(undefined, {
    enabled: !!user,
  });

  // Fetch all auto-generated routes
  const { data: routes, isLoading: routesLoading } = trpc.routes.list.useQuery(undefined, {
    enabled: !!user,
  });

  // Fetch route holders
  const { data: routeHolders, isLoading: holdersLoading } = trpc.routeHolders.list.useQuery(undefined, {
    enabled: !!user,
  });

  if (authLoading || contactsLoading || routesLoading || holdersLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Loading Smart Routing Dashboard...</p>
        </div>
      </div>
    );
  }

  if (!user?.enableSmartRouting) {
    return (
      <div className="container mx-auto py-8">
        <Card>
          <CardHeader>
            <CardTitle>Smart Auto-Routing Not Enabled</CardTitle>
            <CardDescription>
              Enable Smart Auto-Routing in Settings to automatically create weekly routes based on contact schedules.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button onClick={() => setLocation("/settings")}>
              Go to Settings
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Filter contacts with scheduled days
  const scheduledContacts = contacts?.filter(c => c.scheduledDays && c.scheduledDays.trim() !== "") || [];

  // Filter auto-generated routes for current week
  const autoRoutes = routes?.filter(r => r.isAutoGenerated && !r.isArchived) || [];

  // Group routes by route holder
  const routesByHolder: Record<number | string, typeof autoRoutes> = {};
  const unassignedRoutes: typeof autoRoutes = [];

  autoRoutes.forEach(route => {
    if (route.routeHolderId) {
      if (!routesByHolder[route.routeHolderId]) {
        routesByHolder[route.routeHolderId] = [];
      }
      routesByHolder[route.routeHolderId].push(route);
    } else {
      unassignedRoutes.push(route);
    }
  });

  // Calculate total stops per holder
  const getStopCount = (routes: typeof autoRoutes) => {
    return routes.reduce((sum, route) => sum + (route.waypointCount || 0), 0);
  };

  return (
    <div className="container mx-auto py-8 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Smart Auto-Routing Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Current week routes grouped by route holder
          </p>
        </div>
        <Button onClick={() => setLocation("/settings")} variant="outline">
          <Calendar className="h-4 w-4 mr-2" />
          Settings
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Scheduled Contacts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Users className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">{scheduledContacts.length}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Active Routes
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <MapPin className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">{autoRoutes.length}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Stops
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Calendar className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">
                {getStopCount(autoRoutes)}
              </span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Routes by Route Holder */}
      {routeHolders && routeHolders.length > 0 ? (
        <div className="space-y-4">
          {routeHolders.map((holder: any) => {
            const holderRoutes = routesByHolder[holder.id] || [];
            const stopCount = getStopCount(holderRoutes);

            return (
              <Card key={holder.id}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div
                        className="w-4 h-4 rounded"
                        style={{ backgroundColor: holder.defaultStopTypeColor || "#3b82f6" }}
                      />
                      <div>
                        <CardTitle>{holder.name}'s Routes</CardTitle>
                        <CardDescription>
                          {holderRoutes.length} {holderRoutes.length === 1 ? "route" : "routes"}
                          {stopCount > 0 && ` • ${stopCount} total stops`}
                          {holder.defaultStopType && ` • Default: ${holder.defaultStopType}`}
                        </CardDescription>
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  {holderRoutes.length === 0 ? (
                    <p className="text-sm text-muted-foreground">
                      No routes assigned to {holder.name} this week
                    </p>
                  ) : (
                    <div className="space-y-2">
                      {holderRoutes.map(route => (
                        <div
                          key={route.id}
                          className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 cursor-pointer transition-colors"
                          onClick={() => setLocation(`/route/${route.id}`)}
                        >
                          <div className="flex-1">
                            <p className="font-medium">{route.name}</p>
                            <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                              <span>{route.waypointCount || 0} stops</span>
                              {route.totalDistance && (
                                <span>{(route.totalDistance / 1000).toFixed(1)} km</span>
                              )}
                              {route.scheduledDate && (
                                <span>
                                  {new Date(route.scheduledDate).toLocaleDateString('en-US', {
                                    weekday: 'short',
                                    month: 'short',
                                    day: 'numeric'
                                  })}
                                </span>
                              )}
                            </div>
                          </div>
                          <ChevronRight className="h-5 w-5 text-muted-foreground" />
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}

          {/* Unassigned Routes */}
          {unassignedRoutes.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Unassigned Routes</CardTitle>
                <CardDescription>
                  {unassignedRoutes.length} {unassignedRoutes.length === 1 ? "route" : "routes"} without a route holder
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {unassignedRoutes.map(route => (
                    <div
                      key={route.id}
                      className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 cursor-pointer transition-colors"
                      onClick={() => setLocation(`/route/${route.id}`)}
                    >
                      <div className="flex-1">
                        <p className="font-medium">{route.name}</p>
                        <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                          <span>{route.waypointCount || 0} stops</span>
                          {route.totalDistance && (
                            <span>{(route.totalDistance / 1000).toFixed(1)} km</span>
                          )}
                          {route.scheduledDate && (
                            <span>
                              {new Date(route.scheduledDate).toLocaleDateString('en-US', {
                                weekday: 'short',
                                month: 'short',
                                day: 'numeric'
                              })}
                            </span>
                          )}
                        </div>
                      </div>
                      <ChevronRight className="h-5 w-5 text-muted-foreground" />
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      ) : (
        /* No Route Holders - Show All Routes */
        <Card>
          <CardHeader>
            <CardTitle>Auto-Generated Routes</CardTitle>
            <CardDescription>
              Routes automatically created from scheduled contacts
            </CardDescription>
          </CardHeader>
          <CardContent>
            {autoRoutes.length === 0 ? (
              <div className="text-center py-8">
                <p className="text-sm text-muted-foreground mb-4">
                  No auto-generated routes yet. Schedule some contacts to get started!
                </p>
                <Button onClick={() => setLocation("/workspace")}>
                  Go to Contacts
                </Button>
              </div>
            ) : (
              <div className="space-y-2">
                {autoRoutes.map(route => (
                  <div
                    key={route.id}
                    className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 cursor-pointer transition-colors"
                    onClick={() => setLocation(`/route/${route.id}`)}
                  >
                    <div className="flex-1">
                      <p className="font-medium">{route.name}</p>
                      <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                        <span>{route.waypointCount || 0} stops</span>
                        {route.totalDistance && (
                          <span>{(route.totalDistance / 1000).toFixed(1)} km</span>
                        )}
                        {route.scheduledDate && (
                          <span>
                            {new Date(route.scheduledDate).toLocaleDateString('en-US', {
                              weekday: 'short',
                              month: 'short',
                              day: 'numeric'
                            })}
                          </span>
                        )}
                      </div>
                    </div>
                    <ChevronRight className="h-5 w-5 text-muted-foreground" />
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
