import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Calendar, MapPin, Users } from "lucide-react";
import { useLocation } from "wouter";

export default function SmartRoutingDashboard() {
  const { user, loading: authLoading } = useAuth();
  const [, setLocation] = useLocation();

  // Fetch all contacts with scheduled days
  const { data: contacts, isLoading: contactsLoading } = trpc.contacts.list.useQuery(undefined, {
    enabled: !!user,
  });

  // Fetch all auto-generated routes
  const { data: routes, isLoading: routesLoading } = trpc.routes.list.useQuery(undefined, {
    enabled: !!user,
  });

  if (authLoading || contactsLoading || routesLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Loading Smart Routing Dashboard...</p>
        </div>
      </div>
    );
  }

  if (!user?.enableSmartRouting) {
    return (
      <div className="container mx-auto py-8">
        <Card>
          <CardHeader>
            <CardTitle>Smart Auto-Routing Not Enabled</CardTitle>
            <CardDescription>
              Enable Smart Auto-Routing in Settings to automatically create weekly routes based on contact schedules.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button onClick={() => setLocation("/settings")}>
              Go to Settings
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Filter contacts with scheduled days
  const scheduledContacts = contacts?.filter(c => c.scheduledDays && c.scheduledDays.trim() !== "") || [];

  // Filter auto-generated routes
  const autoRoutes = routes?.filter(r => r.isAutoGenerated) || [];

  // Group contacts by day
  const dayNames = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
  const contactsByDay = dayNames.map(day => {
    const dayContacts = scheduledContacts.filter(c => 
      c.scheduledDays?.split(",").map(d => d.trim()).includes(day)
    );
    return { day, contacts: dayContacts };
  });

  return (
    <div className="container mx-auto py-8 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Smart Auto-Routing Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Manage your recurring weekly routes and scheduled contacts
          </p>
        </div>
        <Button onClick={() => setLocation("/settings")} variant="outline">
          <Calendar className="h-4 w-4 mr-2" />
          Settings
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Scheduled Contacts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Users className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">{scheduledContacts.length}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Auto-Generated Routes
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <MapPin className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">{autoRoutes.length}</span>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Active Days
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Calendar className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">
                {contactsByDay.filter(d => d.contacts.length > 0).length}
              </span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Weekly Schedule */}
      <Card>
        <CardHeader>
          <CardTitle>Weekly Schedule</CardTitle>
          <CardDescription>
            Contacts scheduled for each day of the week
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {contactsByDay.map(({ day, contacts }) => (
              <div key={day} className="border rounded-lg p-4">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-semibold text-lg">{day}</h3>
                  <span className="text-sm text-muted-foreground">
                    {contacts.length} {contacts.length === 1 ? "contact" : "contacts"}
                  </span>
                </div>
                
                {contacts.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No contacts scheduled for this day</p>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
                    {contacts.map(contact => (
                      <div
                        key={contact.id}
                        className="flex items-center gap-2 p-2 bg-muted rounded-md"
                      >
                        {contact.photoUrl ? (
                          <img
                            src={contact.photoUrl}
                            alt={contact.contactName}
                            className="h-8 w-8 rounded-full object-cover"
                          />
                        ) : (
                          <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center text-xs font-semibold">
                            {contact.contactName.split(" ").map(n => n[0]).join("").slice(0, 2)}
                          </div>
                        )}
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium truncate">{contact.contactName}</p>
                          {contact.address && (
                            <p className="text-xs text-muted-foreground truncate">{contact.address}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Auto-Generated Routes */}
      <Card>
        <CardHeader>
          <CardTitle>Auto-Generated Routes</CardTitle>
          <CardDescription>
            Routes automatically created from scheduled contacts
          </CardDescription>
        </CardHeader>
        <CardContent>
          {autoRoutes.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No auto-generated routes yet. Schedule some contacts to get started!
            </p>
          ) : (
            <div className="space-y-2">
              {autoRoutes.map(route => (
                <div
                  key={route.id}
                  className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 cursor-pointer"
                  onClick={() => setLocation(`/routes/${route.id}`)}
                >
                  <div className="flex-1">
                    <p className="font-medium">{route.name}</p>
                    <p className="text-sm text-muted-foreground">
                      {route.waypointCount || 0} stops
                      {route.distance && ` • ${(route.distance / 1000).toFixed(1)} km`}
                    </p>
                  </div>
                  <Button variant="ghost" size="sm">
                    View Route
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
