import { describe, expect, it } from "vitest";

describe("Schedule deletion cleanup", () => {
  it("should match routes by scheduledDate instead of name", () => {
    // Test that the SQL query correctly matches dates
    const dayDate = new Date('2025-12-09T00:00:00.000Z');
    const isoDate = dayDate.toISOString().split('T')[0];
    
    expect(isoDate).toBe('2025-12-09');
  });

  it("should handle route holder prefixes in route names", () => {
    // Routes with holder: "Randy - Monday 12/9/2025"
    // Routes without holder: "Monday 12/9/2025"
    // Both should be found by scheduledDate matching
    
    const routeWithHolder = "Randy - Monday 12/9/2025";
    const routeWithoutHolder = "Monday 12/9/2025";
    
    // The fix uses scheduledDate matching instead of name matching
    // so both route name formats will be found correctly
    expect(routeWithHolder).toContain("Monday");
    expect(routeWithoutHolder).toContain("Monday");
  });

  it("should only delete incomplete auto-generated routes", () => {
    // Test conditions for route deletion:
    // 1. isAutoGenerated = true
    // 2. completedAt = null (incomplete)
    // 3. No remaining waypoints (position > 0)
    
    const shouldDelete = {
      isAutoGenerated: true,
      completedAt: null,
      remainingWaypoints: 0
    };
    
    const shouldKeep = {
      isAutoGenerated: false, // Manual route
      completedAt: null,
      remainingWaypoints: 0
    };
    
    expect(shouldDelete.isAutoGenerated && !shouldDelete.completedAt && shouldDelete.remainingWaypoints === 0).toBe(true);
    expect(shouldKeep.isAutoGenerated && !shouldKeep.completedAt && shouldKeep.remainingWaypoints === 0).toBe(false);
  });

  it("should preserve completed routes even if empty", () => {
    const completedRoute = {
      isAutoGenerated: true,
      completedAt: new Date(),
      remainingWaypoints: 0
    };
    
    // Should NOT delete because completedAt is set
    expect(completedRoute.isAutoGenerated && !completedRoute.completedAt && completedRoute.remainingWaypoints === 0).toBe(false);
  });

  it("should preserve routes with remaining waypoints", () => {
    const routeWithWaypoints = {
      isAutoGenerated: true,
      completedAt: null,
      remainingWaypoints: 2
    };
    
    // Should NOT delete because there are still waypoints
    expect(routeWithWaypoints.isAutoGenerated && !routeWithWaypoints.completedAt && routeWithWaypoints.remainingWaypoints === 0).toBe(false);
  });
});
